name: Check that devcontainer builds

on:
  push:
    paths: [ '.devcontainer/Dockerfile' ]

jobs:
  devcontainer-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build devcontainer
        run: docker build -t just-for-testing .devcontainer